[project]
dependencies = [
  "streamlit>=1.48.1",
  "youtube-transcript-api>=1.2.2",
  "yt-dlp>=2025.8.27",
]
description = "YouTube video summarizer"
name = "yt-summerizer"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
